name: cs449
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - filetype=1.2.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.3
  - pytest=8.3.3
  - python=3.12.7
  - pytorch=2.4.1
